name: Deploy dev

on:
  push:
    branches: ["dev_go"]
  workflow_dispatch:
    branches: ["dev_go"]

jobs:
  dev_build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "dev_go"

      - name: Setup Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v .

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              nbtca/saturday_dev:${{ steps.date.outputs.today }}
              nbtca/saturday_dev:latest

#      - name: ssh pipelines
#        uses: cross-the-world/ssh-pipeline@master
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          user: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.ACCESS_TOKEN }}
#          connect_timeout: 10s
#          script: |
#            cd /home/nbtca/
#            docker pull nbtca/saturday_dev:latest
#            docker